### ISSUE TITLE
we never finished this...

### ISSUE THREAD

**Issue by bencalegari** [craigbarstow/nerf-turret-controller#1]
# WTF

**Comment by craigbarstow** [comment]
I'm way better with Node now. I'll crack it open again this weekend and do some poking around.

**Comment by bencalegari** [comment]
Yesssssss I'm down to open up a google hangout and work on it with you if you want. Probably not gonna be doing much this weekend. 

—
Ben Calegari

**Comment by bencalegari** [comment]
..never did get that email @craigbarstow 
![lie](https://media.giphy.com/media/Iu9rM6jqEozoPqbfxn/giphy.gif)
